---
language: python
services: docker

env:
  global:
    - ROLE_NAME: peek
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ${TRAVIS_BUILD_DIR} opnsynid.$ROLE_NAME
  - cd opnsynid.$ROLE_NAME

script:
  # Run tests.
  - molecule test
