---
- name: Converge
  hosts: all
  become: true

  vars:
    peek_install_from_source: false

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: open_synergy.peek
